const PROVIDE_NAME = {
  USER_REPOSITORY: 'USER_REPOSITORY',
  TAG_REPOSITORY: 'TAG_REPOSITORY',
  ROLE_REPOSITORY: 'ROLE_REPOSITORY',
  QUESTION_REPOSITORY: 'QUESTION_REPOSITORY',
  POST_REPOSITORY: 'POST_REPOSITORY',
  POST_TAG_REPOSITORY: 'POST_TAG_REPOSITORY',
  POST_COMMENT_REPOSITORY: 'POST_COMMENT_REPOSITORY',
  POST_CATEGORY_REPOSITORY: 'POST_CATEGORY_REPOSITORY',
  PERMISSION_REPOSITORY: 'PERMISSION_REPOSITORY',
  COMMENT_REPOSITORY: 'COMMENT_REPOSITORY',
  CATEGORY_REPOSITORY: 'CATEGORY_REPOSITORY',
};

export default PROVIDE_NAME;
